# Role: k8s_prereqs/handlers/main.yml
- name: Restart docker
  ansible.builtin.service:
    name: docker
    state: restarted
    enabled: yes

- name: Apply sysctl
  ansible.builtin.command: sysctl --system
