- name: Install keepalived
  apt:
    name: keepalived
    state: present
    update_cache: yes

- name: Deploy keepalived configuration from template
  template:
    src: keepalived.conf.j2
    dest: /etc/keepalived/keepalived.conf

- name: Start keepalived
  service:
    name: keepalived
    state: started
    enabled: yes
