# Role: containerd_install/tasks/main.yml
- name: Install containerd
  apt:
    name: containerd
    state: present
    update_cache: yes
  tags: [containerd]

- name: Ensure /etc/containerd exists
  file:
    path: /etc/containerd
    state: directory
    mode: '0755'
  tags: [containerd]

- name: Generate containerd default config
  shell: containerd config default > /etc/containerd/config.toml
  args:
    creates: /etc/containerd/config.toml
  tags: [containerd]

- name: Enable SystemdCgroup in containerd config
  replace:
    path: /etc/containerd/config.toml
    regexp: 'SystemdCgroup = false'
    replace: 'SystemdCgroup = true'
  tags: [containerd]

- name: Enable and restart containerd
  service:
    name: containerd
    state: restarted
    enabled: yes
  tags: [containerd]