# Role: kubeadm_join_worker/tasks/main.yml
- name: Copy the join command to server location
  ansible.builtin.copy:
    src: ./files/join_commands/join-command
    dest: /tmp/join-command.sh
    mode: '0777'
  tags: [kubeadm_join_worker]
  
- name: Join the node to cluster
  ansible.builtin.command: sh /tmp/join-command.sh
  tags: [kubeadm_join_worker]
  
- name: Start keepalived
  ansible.builtin.service:
    name: keepalived
    state: started
    enabled: yes
  tags: [kubeadm_join_worker]
  
- name: Reboot server
  ansible.builtin.shell: "sleep 2 && reboot"
  async: 1
  poll: 0
  failed_when: false
  become: true
  tags: [kubeadm_join_worker]
  
- name: Wait for server to initiate shutdown
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    state: stopped
    port: 22
  delegate_to: localhost
  tags: [kubeadm_join_worker]
  
- name: Wait for server to come back online
  ansible.builtin.wait_for:
    host: "{{ ansible_host }}"
    state: started
    port: 22
  delegate_to: localhost
  tags: [kubeadm_join_worker]
  