# roles/network_plugin/tasks/main.yml
---
# Idempotent CNI setup for Astra-like hosts
# Copies plugins from /usr/lib/cni to /opt/cni/bin if present.
# Pause is optional and controlled by var `network_plugin_pause_seconds` (default 0).
# All tasks tagged `network_plugin`.

- name: Ensure /opt/cni/bin exists
  ansible.builtin.file:
    path: /opt/cni/bin
    state: directory
    mode: '0755'
  tags: [network_plugin]

- name: Check if /usr/lib/cni exists
  ansible.builtin.stat:
    path: /usr/lib/cni
  register: cni_lib
  tags: [network_plugin]

- name: Optional pause before CNI install
  ansible.builtin.pause:
    seconds: "{{ network_plugin_pause_seconds | default(0) }}"
  when: (network_plugin_pause_seconds | default(0) | int) > 0
  tags: [network_plugin]

- name: Copy CNI plugins from /usr/lib/cni -> /opt/cni/bin (recursive, preserve modes)
  ansible.builtin.copy:
    src: /usr/lib/cni/
    dest: /opt/cni/bin/
    remote_src: true
    mode: preserve
    directory_mode: '0755'
  when: cni_lib.stat.isdir | default(false)
  tags: [network_plugin]

- name: Verify CNI binaries present
  ansible.builtin.find:
    paths: /opt/cni/bin
    file_type: file
    patterns:
      - "*.so"
      - "*"
  register: cni_found
  tags: [network_plugin]

- name: Fail if no CNI plugins copied
  ansible.builtin.fail:
    msg: "No CNI plugins found in /opt/cni/bin. Ensure /usr/lib/cni contains plugins or provide another source."
  when: cni_found.matched | int == 0
  tags: [network_plugin]
