# Role: prepare_apt_sources/tasks/main.yml
- name: Comment out the cdrom line
  lineinfile:
    path: /etc/apt/sources.list
    regexp: '^deb cdrom'
    line: '#deb cdrom:[OS Astra Linux 1.7.5 1.7_x86-64 DVD ]/ 1.7_x86-64 contrib main non-free'
  tags: [apt_sources]

- name: Uncomment the repository base line
  lineinfile:
    path: /etc/apt/sources.list
    regexp: '^#deb https://download.astralinux.ru/astra/stable/1.7_x86-64/repository-base/'
    line: 'deb https://download.astralinux.ru/astra/stable/1.7_x86-64/repository-base/ 1.7_x86-64 main contrib non-free'
  notify: Update apt cache
  tags: [apt_sources]

- name: Uncomment the repository extended line
  lineinfile:
    path: /etc/apt/sources.list
    regexp: '^#deb https://download.astralinux.ru/astra/stable/1.7_x86-64/repository-extended/'
    line: 'deb https://download.astralinux.ru/astra/stable/1.7_x86-64/repository-extended/ 1.7_x86-64 main contrib non-free'
  notify: Update apt cache
  tags: [apt_sources]
