# Role: generate_join_commands/tasks/main.yml
- name: Generate join control-plane command
  shell: kubeadm token create --print-join-command --certificate-key $(kubeadm init phase upload-certs --upload-certs | tail -n 1)
  args:
    executable: /bin/bash
  register: join_command_control
  tags: [join_commands, join_cp_gen]

- name: Save join control-plane command to file
  copy:
    content: "{{ join_command_control.stdout }}"
    dest: ./join-control-command
  delegate_to: localhost
  tags: [join_commands, join_cp_save]

- name: Generate join worker command
  command: kubeadm token create --print-join-command
  register: join_command_worker
  tags: [join_commands, join_worker_gen]

- name: Save join worker command to file
  copy:
    content: "{{ join_command_worker.stdout }}"
    dest: ./join-command
  delegate_to: localhost
  tags: [join_commands, join_worker_save]