- name: Create .kube directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.kube"
    state: directory
    mode: '0700'

- name: Copy admin.conf to local kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ lookup('env', 'HOME') }}/.kube/config"
    remote_src: yes

- name: Set ownership of kube config
  file:
    path: "{{ lookup('env', 'HOME') }}/.kube/config"
    owner: "{{ lookup('pipe', 'id -u') }}"
    group: "{{ lookup('pipe', 'id -g') }}"
    mode: '0600'

