# Role: cert_transfer/tasks/main.yml
- name: Create local directories for certificates
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    recurse: yes
  loop:
    - .files/pki/
    - .files/pki/etcd
  delegate_to: localhost
  tags: [cert_transfer]

- name: Fetch control-plane certs
  ansible.builtin.fetch:
    src: /etc/kubernetes/pki/{{ item }}
    dest: .files/pki/
    flat: yes
  loop:
    - ca.crt
    - ca.key
    - front-proxy-ca.crt
    - front-proxy-ca.key
    - sa.key
    - sa.pub
  tags: [cert_transfer]

- name: Fetch etcd certs
  ansible.builtin.fetch:
    src: /etc/kubernetes/pki/etcd/{{ item }}
    dest: .files/pki/etcd/
    flat: yes
  loop:
    - ca.key
    - ca.crt
  tags: [cert_transfer]