- hosts: all
  remote_user: evil
  become: true
  become_method: sudo
  roles:
    - prepare_apt_sources
    - k8s_prereqs
#     - k8s_install

# - hosts: Kuber_control
#   become: true
#   roles:
#     - keepalived_config
#     - kubeadm_init
#     - cert_transfer
#     - generate_join_commands

# - hosts: Kuber_control
#   become: true
#   roles:
#     - kubeadm_join_master