- name: Common setup on the whole cluster
  hosts: Kuber_control, Kuber_worker
  become: true
  roles:
    - prepare_apt_sources
#     - k8s_prereqs
#     - k8s_install

# - name: Keepalived first on initial control node
#   hosts: Kuber_control[0]
#   become: true
#   roles:
#     - keepalived_config

# - name: Initialize cluster on the first control node
#   hosts: Kuber_control[0]
#   become: true
#   roles:
#     - kubeadm_init
#     - cert_transfer
#     - kubeadm_generate_commands

<<<<<<< HEAD
- name: Join remaining control nodes
  hosts: Kuber_control[1:]
  become: true
  roles:
    - keepalived_config
    - kubeadm_join_master
=======
# - name: Join remaining control nodes
#   hosts: Kuber_control[1:]
#   become: true
#   roles:
#     - keepalived_config
#     - kubeadm_join_master
>>>>>>> e25850f637360e325eaf492b98705d8a0ccf7db5

# - name: Join worker nodes
#   hosts: Kuber_worker
#   become: true
#   roles:
#     - keepalived_config
#     - kubeadm_join_worker

# - name: Idempotent CNI setup for Astra-like hosts
#   hosts: Kuber_control, Kuber_worker
#   become: true
#   roles:
#     - network_plugin