- name: Download Kubernetes signing key
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    dest: /tmp/kubernetes-apt-key.pub

- name: Convert key to GPG format
  command: >
    gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-apt-key.pub
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Add Kubernetes apt repository source
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    state: present
    filename: kubernetes

- name: Install kubelet, kubeadm, and kubectl
  apt:
    name:
      - kubelet
      - kubeadm
      - kubectl
    state: present
    update_cache: yes

- name: Hold kubelet, kubeadm and kubectl at current version
  shell: apt-mark hold kubelet kubeadm kubectl

- name: Ensure kubelet is started and enabled
  systemd:
    name: kubelet
    enabled: yes
    state: started

- name: Remove /etc/machine-id
  file:
    path: /etc/machine-id
    state: absent

- name: Remove /var/lib/dbus/machine-id
  file:
    path: /var/lib/dbus/machine-id
    state: absent

- name: Generate new machine-id
  command: systemd-machine-id-setup
