# Role: kubeadm_init/tasks/main.yml
- name: Create kubeadm init config from template
  ansible.builtin.template:
    src: kubeadm-config.yaml.j2
    dest: /opt/kubeadm-config.yaml
  tags: [kubeadm_init]

- name: Initialize the Kubernetes cluster using kubeadm
  ansible.builtin.command: kubeadm init --config=/opt/kubeadm-config.yaml --ignore-preflight-errors=NumCPU
  register: kubeadm_init_result
  failed_when: kubeadm_init_result.rc != 0
  tags: [kubeadm_init]

- name: Ensure kube config directory exists
  ansible.builtin.file:
    path: "{{ kubeconfig_home }}/.kube"
    state: directory
    owner: "{{ kubeconfig_user }}"
    group: "{{ kubeconfig_group }}"
    mode: '0700'
  tags: [kubeadm_init]

- name: Check admin.conf presence
  ansible.builtin.stat:
    path: /etc/kubernetes/admin.conf
  register: admin_conf
  tags: [kubeadm_init]

- name: Copy admin kubeconfig to user
  ansible.builtin.copy:
    src: /etc/kubernetes/admin.conf
    dest: "{{ kubeconfig_home }}/.kube/config"
    remote_src: yes
    owner: "{{ kubeconfig_user }}"
    group: "{{ kubeconfig_group }}"
    mode: '0644'
  when: admin_conf.stat.exists
  tags: [kubeadm_init]

- name: Ensure Python3 and pip are installed
  ansible.builtin.apt:
    name:
      - python3
      - python3-pip
    state: present
    update_cache: yes
  tags: [kubeadm_init]

- name: Ensure Kubernetes Python client is installed
  ansible.builtin.pip:
    name: kubernetes
    executable: /usr/bin/pip3
  tags: [kubeadm_init]

- name: Apply Weave-Net
  when: admin_conf.stat.exists
  kubernetes.core.k8s:
    state: present
    src: https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml
    kubeconfig: /etc/kubernetes/admin.conf
  tags: [weave_net]
  