- name: Deploy kubeadm config from template
  template:
    src: kubeadm-config.yaml.j2
    dest: /opt/kubeadm-config.yaml

- name: Initialize Kubernetes cluster
  command: kubeadm init --config=/opt/kubeadm-config.yaml

- name: Install Weave CNI plugin
  command: kubectl --kubeconfig /etc/kubernetes/admin.conf apply -f https://github.com/weaveworks/weave/releases/download/v2.8.1/weave-daemonset-k8s.yaml

