# roles/k8s_prereqs/tasks/main.yml
- name: Install docker
  ansible.builtin.apt:
    name: docker.io
    state: present
    update_cache: yes
  tags: [k8s_prereqs]

- name: Remove swap entries from fstab
  ansible.posix.mount:
    path: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none
  tags: [k8s_prereqs]

- name: Disable swap (if any)
  ansible.builtin.command: swapoff -a
  when: ansible_swaptotal_mb | int > 0
  tags: [k8s_prereqs]

- name: Mask all active swap units
  ansible.builtin.shell: "systemctl list-units --type=swap --state=loaded --no-legend | awk '{print $1}' | xargs -r systemctl mask"
  tags: [k8s_prereqs]

- name: Load required kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter
  tags: [k8s_prereqs]

- name: Ensure modules are loaded on boot
  ansible.builtin.copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
  tags: [k8s_prereqs]

- name: Write Kubernetes sysctl params
  ansible.builtin.copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
  notify: Apply sysctl
  tags: [k8s_prereqs]

- name: Install curl
  ansible.builtin.apt:
    name: curl
    state: present
    update_cache: yes
  tags: [k8s_prereqs]

- name: Reboot after prerequisites
  ansible.builtin.reboot:
    msg: "Reboot after k8s prereqs"
    connect_timeout: 5
    reboot_timeout: 600
  when: k8s_prereqs_reboot | default(true)
  tags: [k8s_prereqs]