# roles/k8s_prereqs/tasks/main.yml
- name: Remove swap entries from fstab
  ansible.posix.mount:
    path: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none
  tags: [swap_remove]

- name: Disable swap (if any)
  command: swapoff -a
  when: ansible_swaptotal_mb | int > 0
  tags: [swapoff]

- name: Mask all active swap units
  shell: "systemctl list-units --type=swap --state=loaded --no-legend | awk '{print $1}' | xargs -r systemctl mask"
  args: { warn: false }
  changed_when: false
  tags: [swap_mask]

- name: Load required kernel modules
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter
  tags: [kernel_modules_load]

- name: Ensure modules are loaded on boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
  tags: [modules_persist]

- name: Write Kubernetes sysctl params
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-iptables = 1
      net.bridge.bridge-nf-call-ip6tables = 1
      net.ipv4.ip_forward = 1
  notify: Apply sysctl
  tags: [sysctl_file]

- name: Install curl
  apt:
    name: curl
    state: present
    update_cache: yes
  tags: [utils, curl_install]

- name: Reboot after prerequisites
  reboot:
    msg: "Reboot after k8s prereqs"
    connect_timeout: 5
    reboot_timeout: 600
  when: k8s_prereqs_reboot | default(true)
  tags: [reboot_after_prereqs]