# Role: k8s_prereqs/tasks/main.yml
- name: Disable swap in fstab
  mount:
    name: "{{ item }}"
    fstype: swap
    state: absent
  loop:
    - swap
    - none
  tags: [k8s_prereqs]

- name: Turn off swap
  command: swapoff -a
  tags: [k8s_prereqs]

- name: Mask all active swap units
  shell: "systemctl list-units --type=swap --state=loaded --no-legend | awk '{print $1}' | xargs -r systemctl mask"
  args:
    warn: false
  changed_when: false
  tags: [k8s_prereqs]

- name: Enable required kernel modules
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - br_netfilter
    - overlay
  tags: [k8s_prereqs]

- name: Ensure kernel modules are loaded on boot
  copy:
    dest: /etc/modules-load.d/k8s.conf
    content: |
      overlay
      br_netfilter
  tags: [k8s_prereqs]

- name: Apply sysctl params required by Kubernetes
  copy:
    dest: /etc/sysctl.d/k8s.conf
    content: |
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      net.ipv4.ip_forward = 1
  notify: Reload sysctl
  tags: [k8s_prereqs]

- name: Install curl
  apt:
    name: curl
    state: present
    update_cache: yes
  tags: [utils, k8s_prereqs]

- name: Update apt cache (valid 1 day)
  apt:
    update_cache: yes
    cache_valid_time: 86400
  tags: [apt, k8s_prereqs]

- name: Regenerate machine-id on cloned VMs
  block:
    - file:
        path: /etc/machine-id
        state: absent
    - file:
        path: /var/lib/dbus/machine-id
        state: absent
    - command: systemd-machine-id-setup
  tags: [k8s_prereqs]

- name: Reboot after prerequisites
  reboot:
    msg: "Reboot after k8s prereqs"
    connect_timeout: 5
    reboot_timeout: 600
  when: k8s_prereqs_reboot | default(true)
  tags: [k8s_prereqs]
